logging:
  level:
    phoenix:
      jhbank: DEBUG

spring:
  http:
    encoding:
      charset: UTF-8
  data:
    mongodb:
      uri: mongodb://root:Boluome123@139.198.1.168:11017/boluome?authSource=admin&maxPoolSize=1


redis:
  info:
    ip: 192.168.0.3
    port: 6379
    select: 1
    maxIdle: 6
    Maxtotal: 20
    idleTimeMillis: 10000
    minIdle: 4
    maxWailMills: 2000
    onBorrow: true
    onReturn: true

boluome:
# 支付成功向下分发
  payorder: http://192.168.0.5:21003/paySuccess
#  订单状态
  status: http://192.168.0.5:21003/status
#  成功通知
  refundUrl: http://192.168.0.5:21009/refund/jhbank/success


# 金华银行几个固定的值
jhbank:
  encoding: UTF-8
  signMethod: "01"
  sdkAppId: 2131231
  certId: 1213123
  txnType: 1000
  txnSubType: 100000
  aesWay: "01"
  merId: 8201707120000003
  merName: 上海酷屏
  frontEndUrl: http://dev.api.otosaas.com/order/test
  backEndUrl: http://houtao.com
  txnCcyType: 156
  prePay: https://wt.jhccb.com.cn:6006/ifsp-payweb/prePay
  txnProductId: 5555555