logging:
  level: DEBUG


spring:
  http:
    encoding:
      charset: UTF-8
  data:
    mongodb:
      uri: mongodb://root:Boluome123@139.198.1.168:11017/boluome?authSource=admin&maxPoolSize=1


redis:
  info:
    ip: 192.168.0.3
    port: 6379
    select: 1
    maxIdle: 6
    Maxtotal: 20
    idleTimeMillis: 10000
    minIdle: 4
    maxWailMills: 2000
    onBorrow: true
    onReturn: true

boluome:
# 支付成功向下分发
  payorder: http://192.168.0.5:21003/paySuccess
#  订单状态
  status: http://192.168.0.5:21003/status
#  成功通知
  refundUrl: http://192.168.0.5:21009/refund/jhbank/success
